//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference {
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveCalls", Namespace="http://schemas.datacontract.org/2004/07/DallasPoliceActiveCallsService")]
    [System.SerializableAttribute()]
    public partial class ActiveCalls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NatureOfCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReportingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Beat {
            get {
                return this.BeatField;
            }
            set {
                if ((this.BeatField.Equals(value) != true)) {
                    this.BeatField = value;
                    this.RaisePropertyChanged("Beat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Block {
            get {
                return this.BlockField;
            }
            set {
                if ((this.BlockField.Equals(value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time {
            get {
                return this.Date_TimeField;
            }
            set {
                if ((this.Date_TimeField.Equals(value) != true)) {
                    this.Date_TimeField = value;
                    this.RaisePropertyChanged("Date_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division {
            get {
                return this.DivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionField, value) != true)) {
                    this.DivisionField = value;
                    this.RaisePropertyChanged("Division");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentNumber {
            get {
                return this.IncidentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentNumberField, value) != true)) {
                    this.IncidentNumberField = value;
                    this.RaisePropertyChanged("IncidentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NatureOfCalls {
            get {
                return this.NatureOfCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.NatureOfCallsField, value) != true)) {
                    this.NatureOfCallsField = value;
                    this.RaisePropertyChanged("NatureOfCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportingArea {
            get {
                return this.ReportingAreaField;
            }
            set {
                if ((this.ReportingAreaField.Equals(value) != true)) {
                    this.ReportingAreaField = value;
                    this.RaisePropertyChanged("ReportingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber {
            get {
                return this.UnitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNumberField, value) != true)) {
                    this.UnitNumberField = value;
                    this.RaisePropertyChanged("UnitNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriorityGraph", Namespace="http://schemas.datacontract.org/2004/07/DallasPoliceActiveCallsService")]
    [System.SerializableAttribute()]
    public partial class PriorityGraph : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DallasPoliceActiveCallsServiceReference.IDallasPoliceActiveCallsService")]
    public interface IDallasPoliceActiveCallsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/GetData", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/GetDataResponse")]
        List<DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls> GetData();
        
               
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/CreateData", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/CreateDataResponse")]
        void CreateData(DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls activeCalls);
        
       
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/UpdateData", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/UpdateDataResponse")]
        void UpdateData(DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls activeCalls);
        
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/DeleteData", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/DeleteDataResponse")]
        void DeleteData(string IncidentNumber);
        
       
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/GetDetails", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/GetDetailsResponse")]
        DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls GetDetails(string IncidentNumber);
        
       
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDallasPoliceActiveCallsService/GetPriorityGraphValues", ReplyAction="http://tempuri.org/IDallasPoliceActiveCallsService/GetPriorityGraphValuesResponse" +
            "")]
        List<DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.PriorityGraph> GetPriorityGraphValues();
        
        
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDallasPoliceActiveCallsServiceChannel : DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.IDallasPoliceActiveCallsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DallasPoliceActiveCallsServiceClient : System.ServiceModel.ClientBase<DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.IDallasPoliceActiveCallsService>, DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.IDallasPoliceActiveCallsService {
        
        public DallasPoliceActiveCallsServiceClient() {
        }
        
        public DallasPoliceActiveCallsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DallasPoliceActiveCallsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DallasPoliceActiveCallsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DallasPoliceActiveCallsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls> GetData() {
            return base.Channel.GetData();
        }
        
               
        public void CreateData(DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls activeCalls) {
            base.Channel.CreateData(activeCalls);
        }
        
              
        public void UpdateData(DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls activeCalls) {
            base.Channel.UpdateData(activeCalls);
        }
        
        
        public void DeleteData(string IncidentNumber) {
            base.Channel.DeleteData(IncidentNumber);
        }
        
              
        public DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.ActiveCalls GetDetails(string IncidentNumber) {
            return base.Channel.GetDetails(IncidentNumber);
        }
        
       
        public List<DallasPoliceActiveCalls.DallasPoliceActiveCallsServiceReference.PriorityGraph> GetPriorityGraphValues() {
            return base.Channel.GetPriorityGraphValues();
        }
        
    }
}
